// Generated by https://quicktype.io

export interface AboutPageCMS {
    sectionOneCmsData:   SectionCMSDatum[];
    sectionTwoCmsData:   SectionCMSDatum[];
    sectionThreeCmsData: SectionCMSDatum[];
    sectionFourCmsData:  SectionCMSDatum[];
    faqPageCmsData:      FAQPageCMSDatum[];
    faqData:             FAQDatum[];
}

export interface FAQDatum {
    id:        string;
    createdAt: string;
    updatedAt: string;
    isDeleted: boolean;
    question:  string;
    answer:    string;
}

export interface FAQPageCMSDatum {
    id:        string;
    createdAt: string;
    updatedAt: string;
    isDeleted: boolean;
    title:     string;
    subTitle:  string;
}

export interface SectionCMSDatum {
    id:          string;
    createdAt:   string;
    updatedAt:   string;
    isDeleted:   boolean;
    image:       string;
    title:       string;
    subtitle?:   null;
    description: string;
    buttonText?: string;
    buttonLink?: string;
}
