// Generated by https://quicktype.io

export interface ContactPageCMS {
    id:            string;
    createdAt:     string;
    updatedAt:     string;
    isDeleted:     boolean;
    pageTitle:     string;
    pageSubtitle:  string;
    formTitle:     string;
    formSubTitle:  null;
    mapUrl:        string;
    address:       string;
    email:         string;
    contactNumber: string;
}
