// Generated by https://quicktype.io

export interface BlogList {
    pageCount: null;
    posts:     BLogPost[];
}

export interface BLogPost {
    id:              string;
    createdAt:       string;
    updatedAt:       string;
    isDeleted:       boolean;
    image:           string;
    title:           string;
    authorImage:     string;
    authorName:      string;
    publishedAt:     string;
    blogDescription: string;
    urlSlug:         string;
    totalViews:      number;
}
